services:
    kinerity.bestanswer.controller:
        class: kinerity\bestanswer\controller\main_controller
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@user'
            - '@notification_manager'
            - '%core.root_path%'
            - '%core.php_ext%'

    kinerity.bestanswer.listener:
        class: kinerity\bestanswer\event\main_listener
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    kinerity.bestanswer.notification.type.bestanswer:
        class: kinerity\bestanswer\notification\type\bestanswer
        shared: false
        parent: notification.type.base
        calls:
            - [set_config, ['@config']]
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }

    kinerity.bestanswer.notification.type.notbestanswer:
        class: kinerity\bestanswer\notification\type\notbestanswer
        shared: false
        parent: notification.type.base
        calls:
            - [set_config, ['@config']]
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }
